#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 jvmName
  exit
 fi
java -ea -javaagent:hotswap.jar -cp 'jars/*' \
     -Djava.security.manager -Djava.security.policy=dcvm.policy \
     fr.sorbonne_u.components.examples.reflection.DistributedCVM $1 config.xml